# ARTIE manager parameters
manager:
    number_of_threads:  10
    number_of_runs:     1
    number_of_events:   5000
    seed:               10942
    mode:               "run"   # interactive/run
    detector:           "ear1_lig"
    output_filename:    "ear1_example"
    save_particle_maps: true
    save_primary_info:  true
    save_hits:          true
    save_neutron_data:  true
    save_profile_data:  true
    save_non_detected_neutrons: false

# neutron HP parameters
neutron:
    skip_missing_isotopes:      true
    do_not_adjust_final_state:  true
    use_only_photo_evaporation: true
    neglect_doppler:            true
    produce_fission_fragments:  true
    use_wendt_fission_model:    true
    use_nresp71_model:          true

# argon parameters 
argon:
    use_g4_definition:  false
    argon_36_ratio:     0.334   # %
    argon_38_ratio:     0.063   # %
    argon_40_ratio:     99.603  # %
    lar_density:        1.3954  # g/cm^3
    lar_temperature:    85.0    # K
    lar_pressure:       0.952   # atm

# generator parameters
generator:
    energy_cut_low:         20      # keV
    energy_cut_high:        200     # keV
    t_zero_location:        -30.0   # m

    energy_distribution:
        distribution_file:  "data/resolution13a.root"
        distribution_name:  "tally5"

    beam_profile:
        profile_file:   "data/resolution13a.root"
        profile_name:   "tally15"
        beam_location:  "left"      # left, right, both, profile for LANL, none for nTOF
        
    time_of_flight:
        tof_file:       "data/moderator_hist.root"
        tof_name:       "tally15"   

# ARTIE-I target parameters
target:
    active_volume_material: "liquid_argon"
    target_radius:          0.5    # cm
    target_length:          199.9996      # cm

    target_entrance:	16.0 # cm
    target_x:	2.475 # cm
    target_y:	0.0 # cm

    construct_container:    true
    container_outer_material:   "stainless_steel"
    container_inner_material:   "high_vacuum"
    container_outer_radius: 12.7 # cm
    container_inner_radius: 12.2225 # cm
    container_length:       204.693 # cm

    construct_annulus:          true
    annulus_inner_material:     "liquid_argon"
    annulus_container_material: "stainless_steel"
    annulus_inner_radius:       10.16 # cm
    annulus_container_radius:   9.8552 # cm
    annulus_length:             139.21 # cm
    annulus_face_thickness:     0.3302 # cm

    construct_active_volume_container:    true    # bool
    active_volume_container_material:     "stainless_steel"
    active_volume_container_radius:       1.5875   # cm

    construct_inner_flange_left_side:   true
    inner_flange_left_side_material:    "aluminum"
    inner_flange_left_side_radius:      9.8552 #cm
    inner_flange_left_side_thickness:   0.20066 # cm

    construct_inner_flange_right_side:  true
    inner_flange_right_side_material:   "aluminum"
    inner_flange_right_side_radius:     9.8552 #cm
    inner_flange_right_side_thickness:  0.20066 # cm

    construct_inner_flange_left_side_gap:   true
    inner_flange_left_side_gap_material:    "high_vacuum"
    inner_flange_left_side_gap_thickness:   1.87706 # cm

    construct_inner_flange_right_side_gap:  true
    inner_flange_right_side_gap_material:   "high_vacuum"
    inner_flange_right_side_gap_thickness:  1.87706 # cm

    construct_outer_flange_left_side:   true
    outer_flange_left_side_material:    "aluminum"
    outer_flange_left_side_radius:      12.7 #cm
    outer_flange_left_side_thickness:   0.20066 # cm

    construct_outer_flange_right_side:  true
    outer_flange_right_side_material:   "aluminum"
    outer_flange_right_side_radius:     12.7 #cm
    outer_flange_right_side_thickness:  0.20066 # cm

ear1:



hall:
    # construct_beam_pipe:    true    # bool
    # beam_pipe_material:     "rough_vacuum"
    # beam_material:          "high_vacuum"
    # beam_pipe_inner_radius: 18.0    # cm
    # beam_pipe_outer_radius: 20.0    # cm
    # gap:                    2.5     # m
    # construct_hall:         true    # bool
    # hall_material:          "concrete"
    world_x:                4       # m                 
    world_y:                4       # m
    world_z:                75     # m
    world_material:         "high_vacuum"
    # wall_thickness:         1.0     # m

# ARTIE-II detector
detector:
    detector_type:          "simple"
    construct_detector:     true    # bool
    detector_material:      "water"
    detector_radius:        2.0 # cm
    detector_length:        50.0 # cm
    detector_separation:    6.0 # cm
    detector_entrance:      30.0 # m